config/routes.rb
Rails.application.routes.draw do
  root 'snippets#index'
  resources :snippets, only: [:index, :new, :create, :show]
  get 'snippets/view/:slug' => 'snippets#view', as: :snippets_view
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  validates :body, presence: true
  scope :public_all, -> { where(is_private: false) }
  scope :recent, ->(num) { public_all.order('created_at DESC').limit(num) }
  validates :slug, uniqueness: true, :allow_blank => true
  before_create :generate_slug

  protected

  def generate_slug
    self.slug = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Snippet.exists?(slug: random_token)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def index
    @snippets = Snippet.recent(10)
  end

  def show
    @snippet = Snippet.find(params[:id])
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        # @snippet.generate_slug
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def view
    @snippet = Snippet.where("slug = ?", params[:slug]).first
    unless @snippet.present?
      redirect_to snippets_path, alert: 'Snippet not found. Please try again.'
    end
    render 'show'
  end

  private

  def snippet_params
    params.require(:snippet).permit(:body, :is_private)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnippetViewer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
    <% if @snippet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

          <ul>
            <% @snippet.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, cols: 80, rows: 10 %>
    </div>
    <div class="field">
      <%= f.check_box :is_private %> Private ?
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/snippets/index.html.erb
<div class="snippet-box">

  <table cellpadding="0" cellspacing="0">
    <tr>
      <td>
        Snippets
      </td>
      <td>
        <%= link_to "Create Snippet", new_snippet_path %>
      </td>
    </tr>
  </table>

  <table cellpadding="0" cellspacing="0">

    <% @snippets.each do |snippet| %>
        <tr class="item">
          <td>
            <%= link_to snippet do %>
                <%= truncate(snippet.body, length: 15, separator: ' ') %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/snippets/new.html.erb
<div class="snippet-box">
  <h1>Create Your Snippet</h1>

  <%= render 'form' %>

  <%= link_to 'Back', snippets_path %>

</div>

app/views/snippets/show.html.erb
<div class="snippet-box">
  <p id="notice"><%= notice %></p>

  <div>
    <strong>Body:</strong>

    <div class="body-content">
      <%= @snippet.body %>
    </div>
  </div>

  <div>
    <strong>Share This</strong>

    <div class="url-content">
      <%= snippets_view_url(slug: @snippet.slug) %>
    </div>
  </div>
  <%= link_to 'Back', snippets_path %>
</div>

app/views/snippets/view.html.erb
<%= @snippet.inspect %>